### ISSUE TITLE
`v3.0.20190125` breaks kops 1.10 deploys

### ISSUE THREAD

**Issue by zapman449** [kopeio/etcd-manager#191]
slice of the cluster.spec:

```
  etcdClusters:
  - backups:
      backupStore: s3://$KOPS_STATE_STORE/$KLUSTER_NAME/backups/etcd/main
    etcdMembers:
    - instanceGroup: master-eu-west-1c
      name: -2c
    - instanceGroup: master-eu-west-1b
      name: -2b
    - instanceGroup: master-eu-west-1a
      name: -2a
    manager:
      image: kopeio/etcd-manager:latest
    name: main
    version: 3.1.12
  - backups:
      backupStore: s3://$KOPS_STATE_STORE/$KLUSTER_NAME/backups/etcd/events
    etcdMembers:
    - instanceGroup: master-eu-west-1c
      name: -2c
    - instanceGroup: master-eu-west-1b
      name: -2b
    - instanceGroup: master-eu-west-1a
      name: -2a
    manager:
      image: kopeio/etcd-manager:latest
    name: events
    version: 3.1.12
```

`:latest` points to `v3.0.20190125` verified by SHASUM in `docker images`

Docker logs show:

```
I0226 01:05:54.017737       1 main.go:243] discovered IP address: 192.168.132.131
I0226 01:05:54.017774       1 main.go:248] Setting data dir to /rootfs/mnt/master-vol-078729a1332f034f2
open /etc/kubernetes/pki/etcd-manager/etcd-manager-ca.key: no such file or directory
```

and etcd-manager exits without bringing up etcd.
